### ISSUE TITLE
Additional CI checks (pre-commit)

### ISSUE THREAD

**Issue by BCerki** [button-inc/digital_marketplace#20] opened 2021-12-02 16:59 UTC
- for future consideration: end-of-file-fixer (per review in https://github.com/button-inc/digital_marketplace/pull/11)
- pre-commit?

**Comment by wenzowski** [comment] 2021-12-02 17:21
Is this a dupe of #7? If so, anything we can add that improves clarity of that existing issue

**Comment by BCerki** [comment] 2021-12-02 17:30
> Is this a dupe of #7? If so, anything we can add that improves clarity of that existing issue

I think #7 was to set up pre-commit locally (@BryanGK , is that right?). I intended this one to be add pre-commit to the github action

**Comment by wenzowski** [comment] 2021-12-02 17:55
Makes sense to me, great job breaking a big issue to smaller issues. Let's call #7 done when it has a `.pre-commit-config.yaml` suitable for local use of pre-commit hooks, and call this issue done when those same hooks are enforced as a guardrail via CI? That would mean pulling a [`pre-commit.yml` github action](https://github.com/bcgov/sso-keycloak/blob/dev/.github/workflows/pre-commit.yml) out of #7.

**Comment by BCerki** [comment] 2021-12-02 19:31
The [github action is depreacted](https://github.com/marketplace/actions/pre-commit) and they recommend this instead: https://pre-commit.ci/. You install it on the repo, not as a PR--OK to do that? (Not sure how to ask for "code review" on this, since there isn't actually code.)

**Comment by wenzowski** [comment] 2021-12-02 19:41
Cool! Let's try it out. Let me know if you need someone with elevated permissions to install the app?

**Comment by wenzowski** [comment] 2021-12-02 19:49
I jumped the gun & [clicked the button](https://results.pre-commit.ci/repo/github/409311093). The badge, should we choose to add to our Readme:

[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/button-inc/digital_marketplace/main.svg)](https://results.pre-commit.ci/latest/github/button-inc/digital_marketplace/main)
```markdown
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/button-inc/digital_marketplace/main.svg)](https://results.pre-commit.ci/latest/github/button-inc/digital_marketplace/main)
```

**Comment by BCerki** [comment] 2021-12-02 19:51
I was able to click the button too. It's going to fail until @BryanGK's pre-commit yaml is in

**Closed as completed** 2021-12-03 22:38 UTC
Labels: enhancement
